/**
 * Color theme data — generated from Figma design tokens.
 * Source: resources/tokens/color-semantic-{light,dark}/{hue}.tokens.json
 */

#include "theme_colors.h"

const ThemeColors k_theme_dark[COLOR_THEME_COUNT] = {
  [COLOR_THEME_RED] = {
    .bg = GColorFromHEX(0x000000), .bg_inverted = GColorFromHEX(0xFFFFFF),
    .text_default = GColorFromHEX(0xFF0055), .text_subtle = GColorFromHEX(0xFF5555),
    .text_inverted = GColorFromHEX(0xFFFFFF),
    .icon_default = GColorFromHEX(0xFF5555), .icon_subtle = GColorFromHEX(0xFF0055),
    .border_subtle = GColorFromHEX(0x550000),
    .state_positive = GColorFromHEX(0x00FFAA), .state_warning = GColorFromHEX(0xFFAA00),
    .state_danger = GColorFromHEX(0xFF55FF), .state_inactive = GColorFromHEX(0xAAAAAA),
    .state_disabled = GColorFromHEX(0x555555),
  },
  [COLOR_THEME_ORANGE] = {
    .bg = GColorFromHEX(0x000000), .bg_inverted = GColorFromHEX(0xFFFFFF),
    .text_default = GColorFromHEX(0xFF5500), .text_subtle = GColorFromHEX(0xFFAA00),
    .text_inverted = GColorFromHEX(0xFFFFAA),
    .icon_default = GColorFromHEX(0xFFFFAA), .icon_subtle = GColorFromHEX(0xFFAA00),
    .border_subtle = GColorFromHEX(0xAA5500),
    .state_positive = GColorFromHEX(0x55FFAA), .state_warning = GColorFromHEX(0xFFFF55),
    .state_danger = GColorFromHEX(0xFF0055), .state_inactive = GColorFromHEX(0xAAAAAA),
    .state_disabled = GColorFromHEX(0x555555),
  },
  [COLOR_THEME_YELLOW] = {
    .bg = GColorFromHEX(0x000000), .bg_inverted = GColorFromHEX(0xFFFFFF),
    .text_default = GColorFromHEX(0xFFFF00), .text_subtle = GColorFromHEX(0xFFFFAA),
    .text_inverted = GColorFromHEX(0xFFFFFF),
    .icon_default = GColorFromHEX(0xFFFFAA), .icon_subtle = GColorFromHEX(0xFFFF00),
    .border_subtle = GColorFromHEX(0x555500),
    .state_positive = GColorFromHEX(0x00FF55), .state_warning = GColorFromHEX(0xFF5500),
    .state_danger = GColorFromHEX(0xFF00AA), .state_inactive = GColorFromHEX(0xAAAAAA),
    .state_disabled = GColorFromHEX(0x555555),
  },
  [COLOR_THEME_GREEN] = {
    .bg = GColorFromHEX(0x000000), .bg_inverted = GColorFromHEX(0xFFFFFF),
    .text_default = GColorFromHEX(0x00AA55), .text_subtle = GColorFromHEX(0x00FFAA),
    .text_inverted = GColorFromHEX(0xFFFFFF),
    .icon_default = GColorFromHEX(0x00FFAA), .icon_subtle = GColorFromHEX(0x00AA55),
    .border_subtle = GColorFromHEX(0x005500),
    .state_positive = GColorFromHEX(0x00AAFF), .state_warning = GColorFromHEX(0xFFAA55),
    .state_danger = GColorFromHEX(0xFF5555), .state_inactive = GColorFromHEX(0xAAAAAA),
    .state_disabled = GColorFromHEX(0x555555),
  },
  [COLOR_THEME_CYAN] = {
    .bg = GColorFromHEX(0x000000), .bg_inverted = GColorFromHEX(0xFFFFFF),
    .text_default = GColorFromHEX(0x00FFFF), .text_subtle = GColorFromHEX(0xAAFFFF),
    .text_inverted = GColorFromHEX(0xFFFFFF),
    .icon_default = GColorFromHEX(0x55FFFF), .icon_subtle = GColorFromHEX(0x00AAAA),
    .border_subtle = GColorFromHEX(0x005555),
    .state_positive = GColorFromHEX(0x00FFAA), .state_warning = GColorFromHEX(0xFFAA00),
    .state_danger = GColorFromHEX(0xFF0000), .state_inactive = GColorFromHEX(0xAAAAAA),
    .state_disabled = GColorFromHEX(0x555555),
  },
  [COLOR_THEME_BLUE] = {
    .bg = GColorFromHEX(0x000000), .bg_inverted = GColorFromHEX(0xFFFFFF),
    .text_default = GColorFromHEX(0x0055FF), .text_subtle = GColorFromHEX(0x55AAFF),
    .text_inverted = GColorFromHEX(0x00FFFF),
    .icon_default = GColorFromHEX(0x00FFFF), .icon_subtle = GColorFromHEX(0x0055FF),
    .border_subtle = GColorFromHEX(0x0000FF),
    .state_positive = GColorFromHEX(0x00FF55), .state_warning = GColorFromHEX(0xFFAA55),
    .state_danger = GColorFromHEX(0xFF0055), .state_inactive = GColorFromHEX(0xAAAAAA),
    .state_disabled = GColorFromHEX(0x555555),
  },
  [COLOR_THEME_PURPLE] = {
    .bg = GColorFromHEX(0x000000), .bg_inverted = GColorFromHEX(0xFFFFFF),
    .text_default = GColorFromHEX(0x5555FF), .text_subtle = GColorFromHEX(0xAA55FF),
    .text_inverted = GColorFromHEX(0xFFFFFF),
    .icon_default = GColorFromHEX(0xAA55FF), .icon_subtle = GColorFromHEX(0x5500FF),
    .border_subtle = GColorFromHEX(0x5500AA),
    .state_positive = GColorFromHEX(0xAAFF00), .state_warning = GColorFromHEX(0xFFAA55),
    .state_danger = GColorFromHEX(0xFF0055), .state_inactive = GColorFromHEX(0xAAAAAA),
    .state_disabled = GColorFromHEX(0x555555),
  },
  [COLOR_THEME_PINK] = {
    .bg = GColorFromHEX(0x000000), .bg_inverted = GColorFromHEX(0xFFFFFF),
    .text_default = GColorFromHEX(0xFF00FF), .text_subtle = GColorFromHEX(0xFF55AA),
    .text_inverted = GColorFromHEX(0xFFFFFF),
    .icon_default = GColorFromHEX(0xFF55AA), .icon_subtle = GColorFromHEX(0xFF00FF),
    .border_subtle = GColorFromHEX(0x550055),
    .state_positive = GColorFromHEX(0x55FFAA), .state_warning = GColorFromHEX(0xFFFF55),
    .state_danger = GColorFromHEX(0xFF0055), .state_inactive = GColorFromHEX(0xAAAAAA),
    .state_disabled = GColorFromHEX(0x555555),
  },
};

const ThemeColors k_theme_light[COLOR_THEME_COUNT] = {
  [COLOR_THEME_RED] = {
    .bg = GColorFromHEX(0xFF5555), .bg_inverted = GColorFromHEX(0x000000),
    .text_default = GColorFromHEX(0x550000), .text_subtle = GColorFromHEX(0xAA0000),
    .text_inverted = GColorFromHEX(0x000000),
    .icon_default = GColorFromHEX(0x550000), .icon_subtle = GColorFromHEX(0xAA0000),
    .border_subtle = GColorFromHEX(0xFFAAAA),
    .state_positive = GColorFromHEX(0x0055FF), .state_warning = GColorFromHEX(0xFFFF55),
    .state_danger = GColorFromHEX(0xAA0055), .state_inactive = GColorFromHEX(0xFFAA00),
    .state_disabled = GColorFromHEX(0xFF0000),
  },
  [COLOR_THEME_ORANGE] = {
    .bg = GColorFromHEX(0xFFAA55), .bg_inverted = GColorFromHEX(0x000000),
    .text_default = GColorFromHEX(0xAA5500), .text_subtle = GColorFromHEX(0xFF5500),
    .text_inverted = GColorFromHEX(0x000000),
    .icon_default = GColorFromHEX(0xAA5500), .icon_subtle = GColorFromHEX(0xFF5500),
    .border_subtle = GColorFromHEX(0xFFFF00),
    .state_positive = GColorFromHEX(0x5500FF), .state_warning = GColorFromHEX(0xFF5555),
    .state_danger = GColorFromHEX(0xFF0000), .state_inactive = GColorFromHEX(0xFFFF55),
    .state_disabled = GColorFromHEX(0xFFFFAA),
  },
  [COLOR_THEME_YELLOW] = {
    .bg = GColorFromHEX(0xFFFFAA), .bg_inverted = GColorFromHEX(0x000000),
    .text_default = GColorFromHEX(0x555500), .text_subtle = GColorFromHEX(0xAAAA00),
    .text_inverted = GColorFromHEX(0x000000),
    .icon_default = GColorFromHEX(0x555500), .icon_subtle = GColorFromHEX(0xAAAA00),
    .border_subtle = GColorFromHEX(0xFFFF00),
    .state_positive = GColorFromHEX(0x55AA55), .state_warning = GColorFromHEX(0xFFAA00),
    .state_danger = GColorFromHEX(0xAA0055), .state_inactive = GColorFromHEX(0xAAAA55),
    .state_disabled = GColorFromHEX(0xFFFFFF),
  },
  [COLOR_THEME_GREEN] = {
    .bg = GColorFromHEX(0xAAFFAA), .bg_inverted = GColorFromHEX(0x005500),
    .text_default = GColorFromHEX(0x005500), .text_subtle = GColorFromHEX(0x00AA55),
    .text_inverted = GColorFromHEX(0x00AA00),
    .icon_default = GColorFromHEX(0x005500), .icon_subtle = GColorFromHEX(0x00AA55),
    .border_subtle = GColorFromHEX(0x00FF55),
    .state_positive = GColorFromHEX(0x0055FF), .state_warning = GColorFromHEX(0xFFAA00),
    .state_danger = GColorFromHEX(0xAA0055), .state_inactive = GColorFromHEX(0x55AA55),
    .state_disabled = GColorFromHEX(0x55FFAA),
  },
  [COLOR_THEME_CYAN] = {
    .bg = GColorFromHEX(0xAAFFFF), .bg_inverted = GColorFromHEX(0x0000AA),
    .text_default = GColorFromHEX(0x005555), .text_subtle = GColorFromHEX(0x00AAAA),
    .text_inverted = GColorFromHEX(0x0000AA),
    .icon_default = GColorFromHEX(0x005555), .icon_subtle = GColorFromHEX(0x00AAAA),
    .border_subtle = GColorFromHEX(0x00FFFF),
    .state_positive = GColorFromHEX(0x00AA55), .state_warning = GColorFromHEX(0xFFAA55),
    .state_danger = GColorFromHEX(0xFF0055), .state_inactive = GColorFromHEX(0x55AAAA),
    .state_disabled = GColorFromHEX(0x55FFFF),
  },
  [COLOR_THEME_BLUE] = {
    .bg = GColorFromHEX(0x55AAFF), .bg_inverted = GColorFromHEX(0xFFFFFF),
    .text_default = GColorFromHEX(0x0000AA), .text_subtle = GColorFromHEX(0x0000FF),
    .text_inverted = GColorFromHEX(0x000055),
    .icon_default = GColorFromHEX(0x0000AA), .icon_subtle = GColorFromHEX(0x0055FF),
    .border_subtle = GColorFromHEX(0x00FFFF),
    .state_positive = GColorFromHEX(0x005500), .state_warning = GColorFromHEX(0xFFAA00),
    .state_danger = GColorFromHEX(0xAA0055), .state_inactive = GColorFromHEX(0x005555),
    .state_disabled = GColorFromHEX(0x00AAAA),
  },
  [COLOR_THEME_PURPLE] = {
    .bg = GColorFromHEX(0xAAAAFF), .bg_inverted = GColorFromHEX(0x000055),
    .text_default = GColorFromHEX(0x5500AA), .text_subtle = GColorFromHEX(0x5500FF),
    .text_inverted = GColorFromHEX(0x000055),
    .icon_default = GColorFromHEX(0x5500AA), .icon_subtle = GColorFromHEX(0x5555FF),
    .border_subtle = GColorFromHEX(0xAA55FF),
    .state_positive = GColorFromHEX(0x005500), .state_warning = GColorFromHEX(0xFFFF00),
    .state_danger = GColorFromHEX(0xAA0000), .state_inactive = GColorFromHEX(0xAA00FF),
    .state_disabled = GColorFromHEX(0xAA55AA),
  },
  [COLOR_THEME_PINK] = {
    .bg = GColorFromHEX(0xFFAAFF), .bg_inverted = GColorFromHEX(0x550055),
    .text_default = GColorFromHEX(0x550055), .text_subtle = GColorFromHEX(0xFF00AA),
    .text_inverted = GColorFromHEX(0x5500AA),
    .icon_default = GColorFromHEX(0xAA00AA), .icon_subtle = GColorFromHEX(0xFF55FF),
    .border_subtle = GColorFromHEX(0xFF55FF),
    .state_positive = GColorFromHEX(0x0000FF), .state_warning = GColorFromHEX(0xFFFF00),
    .state_danger = GColorFromHEX(0xAA5500), .state_inactive = GColorFromHEX(0xAA55AA),
    .state_disabled = GColorFromHEX(0xFFFFFF),
  },
};
